seed: 10
enn: 7.0
ens: 7.0
lower: 0.5
delay: 50.0
time_dependent_rates: false
save_lattice_traj: true
enf: 1.0
esf: 1.0
eff: 1.0
muf: 1.0
mun: 5.0
fug: 0.0
temperature: 0.1
diffusion_prefactor: 1.0
fluctuation_prefactor: 1.0
rotational_prefactor: 10.0
height: 10
n_side: 50
amplitude: 0.5
frequency: 5
update_type: global_ens
epsilon: 0.1